---
title: Friedenskirche Memmingen
timezone: Europe/Berlin

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

baseurl: "/FKW/"
exclude:
- README.md
subtitle: 1,2,3, ...

plugins:
  - jekyll-sitemap
